#!/bin/bash
# (C) Copyright 2024 Hewlett Packard Enterprise Development LP
#
# This script will pack a GLM-modified Ubuntu/Debian .ISO file
# and cloud-init packages into a GLM Ubuntu/Debian .tar file.
# The GLM-modified Ubuntu/Debian .ISO file is generated by calling
# hpe-iso-build.sh and passing in the regular Ubuntu/Debian .ISO.
# The cloud-init packages are not present in the Ubuntu/Debian .ISO
# so we will pull the cloud-init package and dependencies
# from the network using aptly.

# Usage:
#  hpe-image-build.sh -i <distro.iso> -o <hpe-customizied-distro.tar>

# command line options            | Description
# ------------------------------- | -----------
# -i <distro.iso>                 | Input a standard Ubuntu/Debian .ISO file
# -o <hpe-customizied-distro.tar> | Output GLM Ubuntu/Debian .tar file
# -n <distro-name>                | Distro name: DEBIAN or UBUNTU.
# -v <distro-ver>                 | Distro version number separated by dots

set -exuo pipefail

UEFI_ORIG_CFG_FILE=""
INPUT_ISO_FILENAME=""
CUSTOM_TAR_FILENAME=""
DISTRO_NAME=""
DISTRO_VER=""
# parse command line parameters
while getopts "i:o:n:v:" opt
do
    case $opt in
        i) INPUT_ISO_FILENAME=$OPTARG
            if [[ ! -f $INPUT_ISO_FILENAME ]]
            then
                echo "ERROR missing image file $INPUT_ISO_FILENAME"
                exit -1
            fi
            ;;
        o) CUSTOM_TAR_FILENAME=$OPTARG ;;
        n) DISTRO_NAME=$OPTARG ;;
        v) DISTRO_VER=$OPTARG ;;
    esac
done

if [ -z "$INPUT_ISO_FILENAME" -o -z "$CUSTOM_TAR_FILENAME" -o -z "$DISTRO_NAME" -o -z "$DISTRO_VER" ]; then
   echo "Usage: $0 -i <distro.iso> -o <hpe-customizied-distro.tar> -d <distro-name> -v <distro-version>"
   exit 1
fi

# generate the .ISO filename
OUTPUT_ISO_FILENAME=$(echo $CUSTOM_TAR_FILENAME | sed -e "s/\.tar/.iso/g")

# convert the Ubuntu/Debian .ISO into the GLM version
./hpe-iso-build.sh -i $INPUT_ISO_FILENAME -n $DISTRO_NAME -o $OUTPUT_ISO_FILENAME

# check to make sure we have the required tools called within this script
for i in aptly
do
  which $i > /dev/null 2>&1
  if [ $? -ne 0 ]
  then
    echo "$i not found. Please install."
    exit -1
  fi
done

# Get the major distro version: 22.04 -> 22
DISTRO_MAJOR_VER=$(echo $DISTRO_VER | sed -e "s/\..*//")

# Setup up the distro repo based on DISTRO_NAME
if [ "${DISTRO_NAME^^}" == "UBUNTU" ]; then

  # Ubuntu
  DISTRO_REPO=http://us.archive.ubuntu.com/ubuntu/

  case $DISTRO_MAJOR_VER in
    20) DISTRO_RELEASE_NAME="focal" ;;
    22) DISTRO_RELEASE_NAME="jammy" ;;
    24) DISTRO_RELEASE_NAME="noble" ;;
    *)
      echo "ERROR unknown major distro version: $DISTRO_MAJOR_VER"
      exit -1
      ;;
  esac

elif [ "${DISTRO_NAME^^}" == "DEBIAN" ]; then

  # Debian
  DISTRO_REPO=https://ftp.debian.org/debian/

  case $DISTRO_MAJOR_VER in
    11) DISTRO_RELEASE_NAME="bullseye" ;;
    12) DISTRO_RELEASE_NAME="bookworm" ;;
    *)
      echo "ERROR unknown major distro version: $DISTRO_MAJOR_VER"
      exit -1
      ;;
  esac

else
  echo "ERROR unknown distro name: $DISTRO_NAME"
  exit -1
fi

# Setup keys for Debian repos
if [ "${DISTRO_NAME^^}" == "DEBIAN" ]; then
  # Add Debian Key (https://keyring.debian.org/)
  gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keyring.debian.org --recv-keys 0x2404C9546E145360

  # Add the Debian Bookworm keys (https://ftp-master.debian.org/keys.html)
  wget -O - https://ftp-master.debian.org/keys/archive-key-${DISTRO_MAJOR_VER}.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import

  # add another key
  gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 F8D2585B8783D481
fi

# generate a Debian repo of cloud-init and dependencies
rm -rf .aptly
aptly mirror create -architectures=amd64 -filter="cloud-init|prometheus-node-exporter|systemd-resolved|ifenslave|lsscsi"  -filter-with-deps $DISTRO_RELEASE_NAME-cloud-init $DISTRO_REPO $DISTRO_RELEASE_NAME main
aptly mirror update $DISTRO_RELEASE_NAME-cloud-init
aptly snapshot create $DISTRO_RELEASE_NAME-cloud-init from mirror $DISTRO_RELEASE_NAME-cloud-init
aptly publish --skip-signing snapshot $DISTRO_RELEASE_NAME-cloud-init

# generate the tarball
cp $OUTPUT_ISO_FILENAME ~/.aptly
tar cvf $CUSTOM_TAR_FILENAME -C ~/.aptly/ $(basename $OUTPUT_ISO_FILENAME) public
